insert into SHIFT (date,start,end) values (CURRENT_DATE(),8,16)
insert into SHIFT (date,start,end) values (CURRENT_DATE(),9,17)
insert into SHIFT (date,start,end) values (CURRENT_DATE(),6,18)
insert into SHIFT (date,start,end) values (CURRENT_DATE(),18,6)

insert into EMPLOYEE (name,job) values ('Vizi Marci','DRIVER')
insert into EMPLOYEE (name,job) values ('Hegyi Józsi','DOCTOR')
insert into EMPLOYEE (name,job) values ('Kuti Béla','MEDIC')
insert into EMPLOYEE (name,job) values ('Tanyasi Zoli','DRIVER')
insert into EMPLOYEE (name,job) values ('Városi Matyi','DOCTOR')
insert into EMPLOYEE (name,job) values ('Földi Elek','MEDIC')

insert into CAR (plate_number,car_type) values ('HHH-001','KIM')
insert into CAR (plate_number,car_type) values ('KKK-002','ROKO')
insert into CAR (plate_number,car_type) values ('RRR-987','ESETKOCSI')
insert into CAR (plate_number,car_type) values ('HHH-002','KIM')